### ISSUE TITLE
Performance Comparison of GraalJS, Javet and Nashorn

### ISSUE THREAD

**Issue by caoccao** [JonHenson/js-engine-performance#1]
I guess you might be interested in this [comparison](https://github.com/caoccao/GraalJS-vs-Javet-vs-Nashorn), as I saw you just opened an issue at GraalJS for a performance issue.

**Comment by ptrthomas** [comment]
piling on and wanted to make sure you are aware of this new project that I am leading: https://github.com/karatelabs/karate-js
